<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="fb_Camming" Id="{8361fd26-60b0-424e-a4d2-1431119063bc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_Camming
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
  fbCamIn       : Tc2_MC2_Camming.MC_CamIn_V2;
  fbCamOut      : Tc2_MC2_Camming.MC_CamOut;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="fb_Camming">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>