<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_CamOut_Empty" Id="{cd80eb01-b0e2-0e5b-0b55-ab0c52f95ff7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CamOut_Empty
VAR_INPUT
  Slave             : REFERENCE TO Tc2_MC2.AXIS_REF;
  Execute           : BOOL;
END_VAR
VAR_OUTPUT
  Busy              : BOOL;
  Error             : BOOL;
  Done              : BOOL;
  ErrorId           : UDINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
Error   := TRUE;
ErrorId := 9999; // function is not activated by compiler def CAM
]]></ST>
    </Implementation>
    <LineIds Name="FB_CamOut_Empty">
      <LineId Id="24" Count="0" />
      <LineId Id="22" Count="1" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>