<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="fb_Camming_Empty" Id="{6f5d090e-57ef-4fde-9a1c-9b1eaa1ab987}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_Camming_Empty
VAR_INPUT
END_VAR
VAR_OUTPUT
  Error   : BOOL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="fb_Camming_Empty">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>