<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="f_GetProgress" Id="{b04d1371-58c5-4697-9b80-ccdeece26464}" SpecialFunc="None">
    <Declaration><![CDATA[// global function to extract e_progress from combined value
FUNCTION f_GetProgress : uint
VAR_INPUT
  state     : UINT;
END_VAR
VAR
  nP        : uint;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
nP := state / E_PROGRESS.PROGRESS_INIT;

f_GetProgress := nP * E_PROGRESS.PROGRESS_INIT;
]]></ST>
    </Implementation>
    <LineIds Name="f_GetProgress">
      <LineId Id="1" Count="4" />
    </LineIds>
  </POU>
</TcPlcObject>