<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAPPING" Id="{e84de69b-ba26-07ad-1592-7be68e226b51}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAPPING
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAPPING">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>