<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.13">
  <POU Name="f_GetProgress" Id="{f04b6c63-a39c-4852-82ad-d63dcf25fbdd}" SpecialFunc="None">
    <Declaration><![CDATA[// global function to extract e_progress from combined value
FUNCTION f_GetProgress : uint
VAR_INPUT
  state     : UINT;
END_VAR
VAR
  nP        : uint;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
nP := state / E_PROGRESS.PROGRESS_INIT;

f_GetProgress := nP * E_PROGRESS.PROGRESS_INIT;
]]></ST>
    </Implementation>
    <LineIds Name="f_GetProgress">
      <LineId Id="1" Count="4" />
    </LineIds>
  </POU>
</TcPlcObject>